import {
  pageRoutesV1,
  headingRoutesV1,
  logoRoutesV1,
  socialRoutesV1,
  bioRoutesV1,
  appLinkRoutesV1,
  linkRouteV1,
  textRoutesV1,
  clipboardButtonRoutesV1,
  audioRoutesV1,
  carouselRoutesV1,
  contactCardRoutesV1,
  contactFormRoutesV1,
  linkToPageRoutesV1,
  // shopifyRouterV1,
  videoRoutesV1,
  imageRoutesV1,
  emailSubscribeRoutesV1,
} from "../handlers/apis/v1/page/index.js";

export {
  pageRoutesV1,
  headingRoutesV1,
  logoRoutesV1,
  socialRoutesV1,
  bioRoutesV1,
  appLinkRoutesV1,
  linkRouteV1,
  textRoutesV1,
  clipboardButtonRoutesV1,
  audioRoutesV1,
  carouselRoutesV1,
  contactCardRoutesV1,
  contactFormRoutesV1,
  linkToPageRoutesV1,
  // shopifyRouterV1,
  videoRoutesV1,
  imageRoutesV1,
  emailSubscribeRoutesV1,
};
